create table role (id bigint generated by default as identity, name varchar(255), primary key (id))
create table task (id bigint generated by default as identity, description varchar(255), score integer not null, status integer not null, title varchar(255), primary key (id))
create table tb_user (id bigint generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id))
create table tb_user_roles (user_id bigint not null, roles_id bigint not null)

alter table tb_user_roles add constraint FK7y4nclm9kbxf0edm7mmtg99as foreign key (roles_id) references role
alter table tb_user_roles add constraint FK19t64ocsol5x06fy2cytp7gey foreign key (user_id) references tb_user

insert into task (id, description, score, status, title) values (default, ?, ?, ?, ?)
insert into tb_user (id, email, name, password) values (default, ?, ?, ?)

drop table if exists role CASCADE
drop table if exists task CASCADE 
drop table if exists tb_user CASCADE 
drop table if exists tb_user_roles CASCADE